apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-2jbg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0018-tenant/tkrw-pr712-0075-0018-app/devfile-sample-2jbg@sha256:a1cf8dc562ecc71463ee051ba0ca7602f2b3d89c91829d47466f3adf675e1b8f
        name: my-nodejs
        resources: {}
status: {}
